/*------------------------------------XDisparadores------------------------------------*/
DROP TRIGGER TR_PROFESORNOMBRE_BI;
DROP TRIGGER TR_CALIFICACIONES_BU;
DROP TRIGGER TR_TAREA_CALIFICACION_BD;
DROP TRIGGER TR_CALIFICACIONFECHA_BI;
DROP TRIGGER TR_CLIENTEEstado_BU;
DROP TRIGGER TR_ESTUDIANTEMatricula_AI;
DROP TRIGGER TR_CLIENTEGratuito_BD;
DROP TRIGGER TR_ESTUDIANTERegistro;
DROP TRIGGER TR_PROFESORProf_BI;
