DROP SEQUENCE SEQ_RECORDATORIOS;
DROP SEQUENCE SEQ_NOTIFICACIONES;
DROP SEQUENCE SEQ_FACTURAS;


DROP view INFOESTUDIANTES;
drop view VISTAESTUDIANTESINSTITUCIONES;
drop view VISTAESTUDIANTESCURSOS;
drop view VISTACLIENTESPREMIUM;
drop view VISTACLIENTESGRATUITOS;
drop view FACTURAS_COMPLETAS;