

CREATE ROLE Jefe_Administrador;
GRANT EXECUTE ON PA_ADMINISTRADOR TO Jefe;

CREATE ROLE Profesor;
GRANT EXECUTE ON PA_PROFESOR TO Profesor;
GRANT SELECT, INSERT, UPDATE, DELETE ON CALIFICACIONES TO Profesor;

CREATE ROLE Estudiante;
GRANT EXECUTE ON PA_ESTUDIANTE TO Estudiante;
GRANT SELECT ON CALIFICACIONES TO Estudiante;
GRANT SELECT ON CURSOS TO Estudiante;
GRANT SELECT ON PROFESORES TO Estudiante;
GRANT SELECT ON RECURSOSADICIONALES TO Estudiante;
GRANT SELECT ON TAREAS TO Estudiante;



SELECT * FROM USER_ROLE_PRIVS;
SELECT * FROM SESSION_ROLES;
grant estudiante to BD1000094692;
revoke estudiante from BD1000094692;
select * from user_role_privs;
