CREATE INDEX Ind_UsuariosEstudiante ON ESTUDIANTES(NOMBRE);
CREATE INDEX Ind_NOMBRECursos ON CURSOS(NOMBRE);
CREATE INDEX Ind_NOMBRETareas ON TAREAS(NOMBRE);
CREATE INDEX Ind_ESTUDIANTECalificaciones ON CALIFICACIONES(ESTUDIANTE);