/*--------------------------------Vistas--------------------------------*/

CREATE OR REPLACE VIEW FACTURAS_COMPLETAS AS
SELECT f.CODIGO AS Codigo, f.USUARIOP, f.FECHA, f.COSTO, f.NUMERODECUOTAS, f.DOCUMENTO, f.TRANSACCION, 
t.NOMBREPROPIETARIO, t.NUMEROTARJETA, t.FECHAVENCIMIENTO, t.CODIGODESEGURIDAD, t.TIPOTARJETA 
FROM FACTURAS f INNER JOIN TARJETAS t ON f.CODIGO = t.CODIGOFACTURA;

