

CREATE ROLE Profesor2;
GRANT EXECUTE ON PA_PROFESOR2 TO Profesor2;
GRANT SELECT, INSERT, UPDATE, DELETE ON CALIFICACIONES TO Profesor;
GRANT SELECT, INSERT, UPDATE, DELETE ON HORARIOS TO Profesor2;
GRANT SELECT, INSERT, UPDATE, DELETE ON CURSOS TO Profesor2;
GRANT SELECT, INSERT, UPDATE, DELETE ON SEGUIMIENTOS TO Profesor2;
GRANT SELECT, INSERT, UPDATE, DELETE ON TAREAS TO Profesor2;
GRANT SELECT, INSERT, UPDATE, DELETE ON RECURSOSADICIONALES TO Profesor2;


CREATE ROLE Administrador2;
GRANT EXECUTE ON PA_ADMINISTRADOR2 TO Administrador2;
GRANT SELECT, INSERT, UPDATE, DELETE ON FACTURAS TO Administrador2;
GRANT SELECT, INSERT, UPDATE, DELETE ON TARJETAS TO Administrador2;
GRANT SELECT, INSERT, UPDATE, DELETE ON NOTIFICACIONESINCUMPLIMIENTOS TO Administrador2;
GRANT SELECT, INSERT, UPDATE, DELETE ON INSTITUCIONES TO Administrador2;
GRANT SELECT, INSERT, UPDATE, DELETE ON ESTUDIANTES TO Administrador2;
GRANT SELECT, INSERT, UPDATE, DELETE ON PROFESORES TO Administrador2;
GRANT SELECT, INSERT, UPDATE, DELETE ON CURSOS TO Administrador2;
GRANT SELECT, INSERT, UPDATE, DELETE ON ESTUDIANTESCURSOS TO Administrador2;



